-- Reconciles the public schema with schema.prisma on databases built by
-- `prisma migrate deploy` (live). Everything below is declared in
-- schema.prisma but was never created by a migration — it only existed on
-- databases synced with `prisma db push`. On live this broke the compliance
-- and moderation features: appeals, grievances, report reference codes and
-- acknowledgement timestamps, removed-content records, guardian attestations.
--
-- Additive and idempotent only (IF NOT EXISTS / duplicate_object guards), so
-- it is a no-op on `db push` databases and on tables the admin panel already
-- creates at runtime (moderation_history, services, admin_*_settings,
-- *_categories, admin_login_attempts). DDL generated by
-- `prisma migrate diff --from-empty --to-schema-datamodel`; nothing dropped.

-- ── ENUMS ──────────────────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE "AppealStatus" AS ENUM ('SUBMITTED', 'UNDER_REVIEW', 'UPHELD', 'OVERTURNED', 'REJECTED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "GrievanceStatus" AS ENUM ('RECEIVED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "RemovedContentType" AS ENUM ('CHAT_MESSAGE', 'FORUM_QUESTION', 'FORUM_ANSWER', 'PROFILE_FIELD');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "Role" AS ENUM ('pwd', 'caregiver', 'therapist', 'ngo', 'volunteer', 'student', 'mentor');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ReportSeverity" AS ENUM ('CRITICAL', 'HIGH', 'ELEVATED', 'MEDIUM', 'LOW');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ReportStatus" AS ENUM ('PENDING', 'REVIEWED', 'ACTIONED', 'DISMISSED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Values added to existing enums (live diff, 2026-10-02).
ALTER TYPE "ConsentType" ADD VALUE IF NOT EXISTS 'TERMS_OF_USE';
ALTER TYPE "ConsentType" ADD VALUE IF NOT EXISTS 'COMMUNITY_GUIDELINES';
ALTER TYPE "ConsentType" ADD VALUE IF NOT EXISTS 'GUARDIAN_CONSENT';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'CSAE';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'SELF_HARM';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'VIOLENCE';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'SEXUAL_CONTENT';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'PRIVACY_VIOLATION';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'HEALTH_MISINFORMATION';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'SCAM_FRAUD';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'ILLEGAL_ACTIVITY';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'IP_INFRINGEMENT';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'BAN_EVASION';

-- ── TABLES ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "registration_records" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phoneNo" TEXT,
    "registeredAt" TIMESTAMP(3) NOT NULL,
    "cancelledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "purgeAfter" TIMESTAMP(3) NOT NULL,
    "chatCleanupAt" TIMESTAMP(3),
    "forumCleanupAt" TIMESTAMP(3),
    "cleanupAttempts" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "registration_records_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "guardian_attestations" (
    "id" TEXT NOT NULL,
    "guardianUserId" TEXT NOT NULL,
    "subjectName" TEXT NOT NULL,
    "subjectIsMinor" BOOLEAN NOT NULL DEFAULT true,
    "relationship" TEXT NOT NULL,
    "conversationId" TEXT,
    "policyVersion" TEXT NOT NULL,
    "ipAddress" TEXT,
    "attestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revokedAt" TIMESTAMP(3),

    CONSTRAINT "guardian_attestations_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "grievance_tickets" (
    "id" TEXT NOT NULL,
    "referenceCode" TEXT NOT NULL,
    "userId" TEXT,
    "contactEmail" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "status" "GrievanceStatus" NOT NULL DEFAULT 'RECEIVED',
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "acknowledgedAt" TIMESTAMP(3),
    "resolvedAt" TIMESTAMP(3),
    "resolutionNote" TEXT,
    "assignedTo" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "grievance_tickets_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "appeals" (
    "id" TEXT NOT NULL,
    "referenceCode" TEXT NOT NULL,
    "appellantId" TEXT NOT NULL,
    "targetType" TEXT NOT NULL,
    "targetId" TEXT NOT NULL,
    "grounds" TEXT NOT NULL,
    "status" "AppealStatus" NOT NULL DEFAULT 'SUBMITTED',
    "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dueBy" TIMESTAMP(3) NOT NULL,
    "respondedAt" TIMESTAMP(3),
    "reviewedBy" TEXT,
    "decisionNote" TEXT,

    CONSTRAINT "appeals_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "message_access_logs" (
    "id" TEXT NOT NULL,
    "adminEmail" TEXT NOT NULL,
    "accessType" TEXT NOT NULL DEFAULT 'context_view',
    "conversationId" TEXT,
    "messageIds" TEXT[],
    "sequenceFrom" BIGINT,
    "sequenceTo" BIGINT,
    "justification" TEXT NOT NULL,
    "reportId" TEXT,
    "ipAddress" TEXT,
    "accessedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "message_access_logs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "removed_content_records" (
    "id" TEXT NOT NULL,
    "contentType" "RemovedContentType" NOT NULL,
    "contentId" TEXT NOT NULL,
    "contentSnapshot" TEXT NOT NULL,
    "authorId" TEXT NOT NULL,
    "conversationId" TEXT,
    "removedBy" TEXT NOT NULL,
    "reason" TEXT,
    "sourceReportId" TEXT,
    "removedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "purgeAfter" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "removed_content_records_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "admin_general_settings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "platform_name" TEXT DEFAULT 'DigiAbility Admin Portal',
    "support_phone" TEXT DEFAULT '+91 88000 12345',
    "email_config" TEXT DEFAULT 'admin@digiability.org',
    "maintenance_mode" BOOLEAN DEFAULT false,
    "supported_languages" JSONB DEFAULT '["English", "Hindi", "Marathi"]',
    "updated_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "admin_general_settings_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "admin_security_settings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "two_fa_enabled" BOOLEAN DEFAULT true,
    "min_password_len" INTEGER DEFAULT 12,
    "require_uppercase" BOOLEAN DEFAULT true,
    "require_numbers" BOOLEAN DEFAULT true,
    "require_special" BOOLEAN DEFAULT true,
    "max_failed_attempts" INTEGER DEFAULT 5,
    "lockout_duration_mins" INTEGER DEFAULT 15,
    "session_timeout_mins" INTEGER DEFAULT 30,
    "updated_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,
    "max_password_len" INTEGER DEFAULT 16,

    CONSTRAINT "admin_security_settings_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "event_categories" (
    "id" TEXT NOT NULL DEFAULT (gen_random_uuid())::text,
    "name" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Active',
    "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "event_categories_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "service_categories" (
    "id" TEXT NOT NULL DEFAULT (gen_random_uuid())::text,
    "name" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Active',
    "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "service_categories_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "moderation_history" (
    "id" TEXT NOT NULL DEFAULT (gen_random_uuid())::text,
    "report_id" TEXT,
    "source" TEXT NOT NULL,
    "content_type" TEXT,
    "content_preview" TEXT,
    "reason" TEXT,
    "author_id" TEXT,
    "author_name" TEXT,
    "reporter_id" TEXT,
    "reporter_name" TEXT,
    "action_taken" TEXT NOT NULL,
    "admin_notes" TEXT,
    "resolved_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "moderation_history_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "services" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "logo" TEXT,
    "image" TEXT,
    "description" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "contactPhone" TEXT,
    "contactEmail" TEXT,
    "contactUrl" TEXT,
    "price" TEXT NOT NULL DEFAULT 'Contact for pricing',
    "availability" TEXT NOT NULL DEFAULT 'By appointment',
    "rating" DECIMAL(65,30) NOT NULL DEFAULT 4.9,
    "reviews" INTEGER NOT NULL DEFAULT 12,
    "verified" BOOLEAN NOT NULL DEFAULT true,
    "status" TEXT NOT NULL DEFAULT 'published',
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "availabilitySchedule" JSONB,

    CONSTRAINT "services_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "admin_login_attempts" (
    "id" TEXT NOT NULL DEFAULT (gen_random_uuid())::text,
    "identifier" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "succeeded" BOOLEAN NOT NULL DEFAULT false,
    "attemptedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "admin_login_attempts_pkey" PRIMARY KEY ("id")
);

-- ── COLUMNS ──────────────────────────────────────────────────
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "roles" "Role"[] DEFAULT ARRAY[]::"Role"[];
ALTER TABLE "forum_reports" ADD COLUMN IF NOT EXISTS "referenceCode" TEXT;
ALTER TABLE "forum_reports" ADD COLUMN IF NOT EXISTS "acknowledgedAt" TIMESTAMP(3);
ALTER TABLE "forum_reports" ADD COLUMN IF NOT EXISTS "actionedAt" TIMESTAMP(3);
ALTER TABLE "forum_reports" ADD COLUMN IF NOT EXISTS "status" "ReportStatus" NOT NULL DEFAULT 'PENDING';
ALTER TABLE "forum_reports" ADD COLUMN IF NOT EXISTS "severity" "ReportSeverity" NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE "forum_reports" ADD COLUMN IF NOT EXISTS "reviewedBy" TEXT;
ALTER TABLE "forum_reports" ADD COLUMN IF NOT EXISTS "reviewedAt" TIMESTAMP(3);
ALTER TABLE "user_reports" ADD COLUMN IF NOT EXISTS "referenceCode" TEXT;
ALTER TABLE "user_reports" ADD COLUMN IF NOT EXISTS "acknowledgedAt" TIMESTAMP(3);
ALTER TABLE "user_reports" ADD COLUMN IF NOT EXISTS "actionedAt" TIMESTAMP(3);
ALTER TABLE "user_reports" ADD COLUMN IF NOT EXISTS "severity" "ReportSeverity" NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE "forum_notifications" ADD COLUMN IF NOT EXISTS "auditLogId" TEXT;
ALTER TABLE "admin_audit_log" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT;

-- ── INDEXES ──────────────────────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS "forum_reports_referenceCode_key" ON "forum_reports"("referenceCode");
CREATE UNIQUE INDEX IF NOT EXISTS "user_reports_referenceCode_key" ON "user_reports"("referenceCode");
CREATE INDEX IF NOT EXISTS "forum_reports_status_createdAt_idx" ON "forum_reports"("status", "createdAt" DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "registration_records_userId_key" ON "registration_records"("userId");
CREATE INDEX IF NOT EXISTS "registration_records_purgeAfter_idx" ON "registration_records"("purgeAfter");
CREATE INDEX IF NOT EXISTS "registration_records_chatCleanupAt_idx" ON "registration_records"("chatCleanupAt");
CREATE INDEX IF NOT EXISTS "registration_records_forumCleanupAt_idx" ON "registration_records"("forumCleanupAt");
CREATE INDEX IF NOT EXISTS "guardian_attestations_guardianUserId_idx" ON "guardian_attestations"("guardianUserId");
CREATE INDEX IF NOT EXISTS "guardian_attestations_conversationId_idx" ON "guardian_attestations"("conversationId");
CREATE UNIQUE INDEX IF NOT EXISTS "grievance_tickets_referenceCode_key" ON "grievance_tickets"("referenceCode");
CREATE INDEX IF NOT EXISTS "grievance_tickets_status_receivedAt_idx" ON "grievance_tickets"("status", "receivedAt");
CREATE INDEX IF NOT EXISTS "grievance_tickets_acknowledgedAt_idx" ON "grievance_tickets"("acknowledgedAt");
CREATE UNIQUE INDEX IF NOT EXISTS "appeals_referenceCode_key" ON "appeals"("referenceCode");
CREATE INDEX IF NOT EXISTS "appeals_status_submittedAt_idx" ON "appeals"("status", "submittedAt");
CREATE INDEX IF NOT EXISTS "appeals_targetType_targetId_idx" ON "appeals"("targetType", "targetId");
CREATE INDEX IF NOT EXISTS "message_access_logs_adminEmail_accessedAt_idx" ON "message_access_logs"("adminEmail", "accessedAt" DESC);
CREATE INDEX IF NOT EXISTS "message_access_logs_conversationId_idx" ON "message_access_logs"("conversationId");
CREATE INDEX IF NOT EXISTS "message_access_logs_accessType_accessedAt_idx" ON "message_access_logs"("accessType", "accessedAt" DESC);
CREATE INDEX IF NOT EXISTS "removed_content_records_purgeAfter_idx" ON "removed_content_records"("purgeAfter");
CREATE INDEX IF NOT EXISTS "removed_content_records_authorId_idx" ON "removed_content_records"("authorId");
CREATE INDEX IF NOT EXISTS "removed_content_records_contentType_contentId_idx" ON "removed_content_records"("contentType", "contentId");
CREATE UNIQUE INDEX IF NOT EXISTS "event_categories_name_key" ON "event_categories"("name");
CREATE UNIQUE INDEX IF NOT EXISTS "service_categories_name_key" ON "service_categories"("name");
CREATE INDEX IF NOT EXISTS "admin_login_attempts_identifier_attemptedAt_idx" ON "admin_login_attempts"("identifier", "attemptedAt" DESC);

-- ── FKS ──────────────────────────────────────────────────
DO $$ BEGIN
  ALTER TABLE "guardian_attestations" ADD CONSTRAINT "guardian_attestations_guardianUserId_fkey" FOREIGN KEY ("guardianUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "grievance_tickets" ADD CONSTRAINT "grievance_tickets_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "appeals" ADD CONSTRAINT "appeals_appellantId_fkey" FOREIGN KEY ("appellantId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

