// AUTO-GENERATED by scripts/sync-legal-docs.js — DO NOT EDIT BY HAND.
// Source: docs/legal/  •  Regenerate with: npm run sync:legal

// The server never needs the document text — only the version it must stamp on
// consent records and compare against to decide whether re-acceptance is due.

/** Version of the published policy set. Must match docs/legal/manifest.json. */
export const POLICY_VERSION = "2026-09-06";
